FROM gcc:12

WORKDIR /

COPY ./build-dev.sh /

RUN apt-get update && \
    apt-get install -y cmake \
    libssl-dev \
    libcpprest-dev \
    libc++-dev
RUN apt-get install -y libboost-dev \
    libboost-thread-dev \
    libboost-timer-dev \
    libboost-chrono-dev
RUN apt-get install -y libomp-dev \
    libopenblas-dev \
    libgtest-dev \
    libgflags-dev

CMD ./build-dev.sh