global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nodes_metrics'
    static_configs:
      - targets:
        - 'coordinator:8080'
        - 'writer:8080'
        - 'searcher_1:8080'
        - 'searcher_2:8080'

  - job_name: 'node_exporter'
    static_configs:
      - targets:
        - 'node_exporter:9100'

  - job_name: 'minio'
    static_configs:
      - targets:
        - 'minio:9000'
    metrics_path: /minio/v2/metrics/node
    scheme: http

  - job_name: 'etcd'
    static_configs:
      - targets:
        - 'etcd:2379'
    metrics_path: /metrics
    scheme: http