name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup Submodules
      run: |
        git submodule update --init --recursive

    - name: Install Dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install gcc libomp openblas faiss googletest cmake gflags

    - name: Install Dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libomp-dev libopenblas-dev libfaiss-dev libgtest-dev libgflags-dev

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        if [[ "$RUNNER_OS" == "macOS" ]]; then
          cmake -G "Xcode" -DCMAKE_BUILD_TYPE=Debug ..
        else
          cmake -DCMAKE_BUILD_TYPE=Debug ..
        fi

    - name: Build
      run: |
        cd build
        cmake --build . --config Debug

    - name: Run Tests
      run: |
        cd build
        ctest --output-on-failure
