name: Build and Test Operator

on:
  push:
    branches: [ "main" ]
    paths:
      - 'kube-operator/**'
      - '.github/workflows/build-operator.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'kube-operator/**'
      - '.github/workflows/build-operator.yml'

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/vecodex-operator
  IMAGE_TAG_PREFIX: git

jobs:
  build_operator:
    name: Build Kubernetes Operator
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_image_tag.outputs.tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'kube-operator/go.mod'
          cache-dependency-path: 'kube-operator/go.sum'

      - name: Set image tag
        id: set_image_tag
        run: echo "tag=${{ env.IMAGE_TAG_PREFIX }}-${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push operator Docker image
        working-directory: ./kube-operator
        run: |
          make docker-build IMG=${{ env.IMAGE_NAME }}:${{ steps.set_image_tag.outputs.tag }}
          docker push ${{ env.IMAGE_NAME }}:${{ steps.set_image_tag.outputs.tag }}

  run_e2e_tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    needs: build_operator 
    # Ensure this job only runs if the build_operator job succeeded and produced an image tag
    if: needs.build_operator.result == 'success' && needs.build_operator.outputs.image_tag != ''
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'kube-operator/go.mod'
          cache-dependency-path: 'kube-operator/go.sum'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up KinD cluster
        uses: helm/kind-action@v1.10.0
       
      - name: Load Docker image into KinD cluster
        run: kind load docker-image ${{ env.IMAGE_NAME }}:${{ needs.build_operator.outputs.image_tag }} --name kind

      - name: Run E2E tests
        working-directory: ./kube-operator
        run: IMG=${{ env.IMAGE_NAME }}:${{ needs.build_operator.outputs.image_tag }} make test-e2e
